// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Barrio
{
    public int IdBarrio { get; set; }

    public string Barrio1 { get; set; }

    public int? Localidad { get; set; }

    public virtual ICollection<Direccione> Direcciones { get; set; } = new List<Direccione>();

    public virtual Localidade LocalidadNavigation { get; set; }
}