// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Clasificacione
{
    public int IdClasificacion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Comentario> Comentarios { get; set; } = new List<Comentario>();
}