// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Comentario
{
    public int IdComentario { get; set; }

    public string Descripcion { get; set; }

    public int? IdClasificacion { get; set; }

    public int? IdInquilino { get; set; }

    public int? IdInmueble { get; set; }

    public virtual ICollection<DetallesInmueble> DetallesInmuebles { get; set; } = new List<DetallesInmueble>();

    public virtual Clasificacione IdClasificacionNavigation { get; set; }

    public virtual Inmueble IdInmuebleNavigation { get; set; }

    public virtual Inquilino IdInquilinoNavigation { get; set; }
}