// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Contrato
{
    public int IdContrato { get; set; }

    public int? IdPropietario { get; set; }

    public int? IdInquilino { get; set; }

    public int? IdInmueble { get; set; }

    public virtual Inmueble IdInmuebleNavigation { get; set; }

    public virtual Inquilino IdInquilinoNavigation { get; set; }

    public virtual Propietario IdPropietarioNavigation { get; set; }

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();
}