// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class DetallesInmueble
{
    public int IdDetalleInmueble { get; set; }

    public int? IdInmueble { get; set; }

    public int? IdDireccion { get; set; }

    public int? Ambientes { get; set; }

    public decimal? PrecioVenta { get; set; }

    public decimal? PrecioAlquiler { get; set; }

    public string CaracteristicasTecnicas { get; set; }

    public string Imagen { get; set; }

    public int? IdTipoInmueble { get; set; }

    public int? IdComentario { get; set; }

    public int? IdDisponible { get; set; }

    public virtual Comentario IdComentarioNavigation { get; set; }

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual Disponible IdDisponibleNavigation { get; set; }

    public virtual Inmueble IdInmuebleNavigation { get; set; }

    public virtual TiposInmueble IdTipoInmuebleNavigation { get; set; }

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();
}