// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class DetallesRecibo
{
    public int IdDetalleRecibo { get; set; }

    public int? NroRecibo { get; set; }

    public int? IdConcepto { get; set; }

    public int? IdMoneda { get; set; }

    public decimal? MontoTotal { get; set; }

    public string Comprobante { get; set; }

    public virtual ConceptosPago IdConceptoNavigation { get; set; }

    public virtual Moneda IdMonedaNavigation { get; set; }

    public virtual Recibo NroReciboNavigation { get; set; }
}