// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Direccione
{
    public int IdDireccion { get; set; }

    public string Calle { get; set; }

    public string Numeracion { get; set; }

    public string CodigoPostal { get; set; }

    public int? IdBarrio { get; set; }

    public virtual ICollection<DetallesInmueble> DetallesInmuebles { get; set; } = new List<DetallesInmueble>();

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<Inquilino> Inquilinos { get; set; } = new List<Inquilino>();

    public virtual ICollection<Obrero> Obreros { get; set; } = new List<Obrero>();

    public virtual ICollection<Propietario> Propietarios { get; set; } = new List<Propietario>();
}