// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Disponible
{
    public int IdDisponible { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<DetallesInmueble> DetallesInmuebles { get; set; } = new List<DetallesInmueble>();
}