// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Inmueble
{
    public int IdInmueble { get; set; }

    public string NombreInmueble { get; set; }

    public string Descripcion { get; set; }

    public int? IdPropietario { get; set; }

    public int? IdInquilino { get; set; }

    public int? IdLibreDeuda { get; set; }

    public virtual ICollection<Comentario> Comentarios { get; set; } = new List<Comentario>();

    public virtual ICollection<Contrato> Contratos { get; set; } = new List<Contrato>();

    public virtual ICollection<DetallesInmueble> DetallesInmuebles { get; set; } = new List<DetallesInmueble>();

    public virtual Inquilino IdInquilinoNavigation { get; set; }

    public virtual LibreDeudum IdLibreDeudaNavigation { get; set; }

    public virtual Propietario IdPropietarioNavigation { get; set; }
}