// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Inquilino
{
    public int IdInquilino { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? IdTipoDoc { get; set; }

    public string Cbu { get; set; }

    public int? IdDireccion { get; set; }

    public string Telefono { get; set; }

    public string MailContacto { get; set; }

    public virtual ICollection<Comentario> Comentarios { get; set; } = new List<Comentario>();

    public virtual ICollection<Contrato> Contratos { get; set; } = new List<Contrato>();

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual TiposDoc IdTipoDocNavigation { get; set; }

    public virtual ICollection<Inmueble> Inmuebles { get; set; } = new List<Inmueble>();

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();
}