// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Inmobiliaria.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Inmobiliaria.Models
{
    public partial interface IPropiedades_InmobiliariasContextProcedures
    {
        Task<List<pa_contratos_detalladosResult>> pa_contratos_detalladosAsync(int? idPropietario, int? idInquilino, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pa_contratos_vigentesResult>> pa_contratos_vigentesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pa_recibos_por_inquilinoResult>> pa_recibos_por_inquilinoAsync(int? idInquilino, DateOnly? desde, DateOnly? hasta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
