// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Localidade
{
    public int IdLocalidad { get; set; }

    public string Localidad { get; set; }

    public int? Provincia { get; set; }

    public virtual ICollection<Barrio> Barrios { get; set; } = new List<Barrio>();

    public virtual Provincia ProvinciaNavigation { get; set; }
}