// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Moneda
{
    public int IdMoneda { get; set; }

    public string TipoMoneda { get; set; }

    public virtual ICollection<DetallesRecibo> DetallesRecibos { get; set; } = new List<DetallesRecibo>();

    public virtual ICollection<TiposCambio> TiposCambios { get; set; } = new List<TiposCambio>();
}