// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Obrero
{
    public int IdObrero { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? IdTipoDoc { get; set; }

    public string Cbu { get; set; }

    public int? IdDireccion { get; set; }

    public string Telefono { get; set; }

    public string MailContacto { get; set; }

    public int? IdTipoObrero { get; set; }

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual TiposDoc IdTipoDocNavigation { get; set; }

    public virtual TipoObrero IdTipoObreroNavigation { get; set; }
}