// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inmobiliaria.Models
{
    public partial class pa_contratos_detalladosResult
    {
        public int Id_contrato { get; set; }
        [StringLength(52)]
        public string Propietario { get; set; }
        [StringLength(52)]
        public string Inquilino { get; set; }
        [StringLength(500)]
        public string Nombre_Inmueble { get; set; }
        [StringLength(101)]
        public string Direccion { get; set; }
        [StringLength(50)]
        public string Barrio { get; set; }
        [StringLength(50)]
        public string Localidad { get; set; }
        public int? Ambientes { get; set; }
        [Column("Precio_Alquiler", TypeName = "decimal(18,4)")]
        public decimal? Precio_Alquiler { get; set; }
        [Column("Precio_Venta", TypeName = "decimal(18,4)")]
        public decimal? Precio_Venta { get; set; }
    }
}
