// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inmobiliaria.Models
{
    public partial class pa_recibos_por_inquilinoResult
    {
        public int Nro_Recibo { get; set; }
        public DateOnly? fecha { get; set; }
        [StringLength(50)]
        public string Estado_Recibo { get; set; }
        public int? Id_Contrato { get; set; }
        [StringLength(52)]
        public string Propietario { get; set; }
        [StringLength(20)]
        public string Tipo_Pago { get; set; }
        public int? ID_Concepto { get; set; }
        [StringLength(25)]
        public string Concepto { get; set; }
        [StringLength(25)]
        public string Moneda { get; set; }
        [Column("Monto_Total", TypeName = "decimal(20,2)")]
        public decimal? Monto_Total { get; set; }
    }
}
