// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Inmobiliaria.Models;

public partial class Propiedades_InmobiliariasContext : DbContext
{
    public Propiedades_InmobiliariasContext(DbContextOptions<Propiedades_InmobiliariasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Barrio> Barrios { get; set; }

    public virtual DbSet<Clasificacione> Clasificaciones { get; set; }

    public virtual DbSet<Comentario> Comentarios { get; set; }

    public virtual DbSet<ConceptosPago> ConceptosPagos { get; set; }

    public virtual DbSet<Contrato> Contratos { get; set; }

    public virtual DbSet<DetallesInmueble> DetallesInmuebles { get; set; }

    public virtual DbSet<DetallesRecibo> DetallesRecibos { get; set; }

    public virtual DbSet<Direccione> Direcciones { get; set; }

    public virtual DbSet<Disponible> Disponibles { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<Inmueble> Inmuebles { get; set; }

    public virtual DbSet<Inquilino> Inquilinos { get; set; }

    public virtual DbSet<LibreDeudum> LibreDeuda { get; set; }

    public virtual DbSet<Localidade> Localidades { get; set; }

    public virtual DbSet<Moneda> Monedas { get; set; }

    public virtual DbSet<Obrero> Obreros { get; set; }

    public virtual DbSet<Propietario> Propietarios { get; set; }

    public virtual DbSet<Provincia> Provincias { get; set; }

    public virtual DbSet<Recibo> Recibos { get; set; }

    public virtual DbSet<Servicio> Servicios { get; set; }

    public virtual DbSet<TipoObrero> TipoObreros { get; set; }

    public virtual DbSet<TiposCambio> TiposCambios { get; set; }

    public virtual DbSet<TiposDoc> TiposDocs { get; set; }

    public virtual DbSet<TiposEmpleado> TiposEmpleados { get; set; }

    public virtual DbSet<TiposInmueble> TiposInmuebles { get; set; }

    public virtual DbSet<TiposPago> TiposPagos { get; set; }

    public virtual DbSet<Venta> Ventas { get; set; } = null!;

    public virtual DbSet<Comision> Comisiones { get; set; } = null!;
    public object Propietario { get; internal set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barrio>(entity =>
        {
            entity.HasKey(e => e.IdBarrio).HasName("PK_ID_barrio");

            entity.Property(e => e.IdBarrio).HasColumnName("ID_barrio");
            entity.Property(e => e.Barrio1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("barrio");
            entity.Property(e => e.Localidad).HasColumnName("localidad");

            entity.HasOne(d => d.LocalidadNavigation).WithMany(p => p.Barrios)
                .HasForeignKey(d => d.Localidad)
                .HasConstraintName("FK_Barrio_Localidad");
        });

        modelBuilder.Entity<Clasificacione>(entity =>
        {
            entity.HasKey(e => e.IdClasificacion).HasName("PK_id_clasificacion");

            entity.Property(e => e.IdClasificacion).HasColumnName("Id_clasificacion");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Comentario>(entity =>
        {
            entity.HasKey(e => e.IdComentario).HasName("PK_ID_Comentario");

            entity.ToTable("COMENTARIOS");

            entity.Property(e => e.IdComentario).HasColumnName("ID_Comentario");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IdClasificacion).HasColumnName("ID_Clasificacion");
            entity.Property(e => e.IdInmueble).HasColumnName("ID_Inmueble");
            entity.Property(e => e.IdInquilino).HasColumnName("ID_Inquilino");

            entity.HasOne(d => d.IdClasificacionNavigation).WithMany(p => p.Comentarios)
                .HasForeignKey(d => d.IdClasificacion)
                .HasConstraintName("FK_Comentario_Clasificacion");

            entity.HasOne(d => d.IdInmuebleNavigation).WithMany(p => p.Comentarios)
                .HasForeignKey(d => d.IdInmueble)
                .HasConstraintName("FK_Comentario_Inmueble");

            entity.HasOne(d => d.IdInquilinoNavigation).WithMany(p => p.Comentarios)
                .HasForeignKey(d => d.IdInquilino)
                .HasConstraintName("FK_Comentario_Inquilino");
        });

        modelBuilder.Entity<ConceptosPago>(entity =>
        {
            entity.HasKey(e => e.IdConcepto).HasName("PK_ID_Concepto");

            entity.ToTable("Conceptos_Pagos");

            entity.Property(e => e.IdConcepto).HasColumnName("ID_Concepto");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Contrato>(entity =>
        {
            entity.HasKey(e => e.IdContrato).HasName("pk_id_contrato");

            entity.Property(e => e.IdContrato).HasColumnName("Id_contrato");
            entity.Property(e => e.IdInmueble).HasColumnName("ID_Inmueble");
            entity.Property(e => e.IdInquilino).HasColumnName("ID_Inquilino");
            entity.Property(e => e.IdPropietario).HasColumnName("ID_Propietario");

            entity.HasOne(d => d.IdInmuebleNavigation).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.IdInmueble)
                .HasConstraintName("fk_id_Inmuebles");

            entity.HasOne(d => d.IdInquilinoNavigation).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.IdInquilino)
                .HasConstraintName("fk_id_inquilino");

            entity.HasOne(d => d.IdPropietarioNavigation).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.IdPropietario)
                .HasConstraintName("fk_id_propietario");
        });

        modelBuilder.Entity<DetallesInmueble>(entity =>
        {
            entity.HasKey(e => e.IdDetalleInmueble).HasName("PK_ID_detalle_inmueble");

            entity.ToTable("Detalles_Inmuebles");

            entity.Property(e => e.IdDetalleInmueble).HasColumnName("ID_detalle_inmueble");
            entity.Property(e => e.CaracteristicasTecnicas)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("Caracteristicas_Tecnicas");
            entity.Property(e => e.IdComentario).HasColumnName("ID_Comentario");
            entity.Property(e => e.IdDireccion).HasColumnName("ID_DIRECCION");
            entity.Property(e => e.IdDisponible).HasColumnName("ID_Disponible");
            entity.Property(e => e.IdInmueble).HasColumnName("ID_INMUEBLE");
            entity.Property(e => e.IdTipoInmueble).HasColumnName("Id_tipo_inmueble");
            entity.Property(e => e.Imagen)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("imagen");
            entity.Property(e => e.PrecioAlquiler)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("Precio_Alquiler");
            entity.Property(e => e.PrecioVenta)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("Precio_Venta");

            entity.HasOne(d => d.IdComentarioNavigation).WithMany(p => p.DetallesInmuebles)
                .HasForeignKey(d => d.IdComentario)
                .HasConstraintName("FK_Detalle_Comentario");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.DetallesInmuebles)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Detalle_Direccion");

            entity.HasOne(d => d.IdDisponibleNavigation).WithMany(p => p.DetallesInmuebles)
                .HasForeignKey(d => d.IdDisponible)
                .HasConstraintName("FK_Detalle_Disponible");

            entity.HasOne(d => d.IdInmuebleNavigation).WithMany(p => p.DetallesInmuebles)
                .HasForeignKey(d => d.IdInmueble)
                .HasConstraintName("FK_Detalle_Inmueble");

            entity.HasOne(d => d.IdTipoInmuebleNavigation).WithMany(p => p.DetallesInmuebles)
                .HasForeignKey(d => d.IdTipoInmueble)
                .HasConstraintName("FK_Detalle_tipo_inmueble");
        });

        modelBuilder.Entity<DetallesRecibo>(entity =>
        {
            entity.HasKey(e => e.IdDetalleRecibo).HasName("PK_ID_Detalle_Recibo");

            entity.ToTable("Detalles_Recibo");

            entity.Property(e => e.IdDetalleRecibo).HasColumnName("ID_Detalle_Recibo");
            entity.Property(e => e.Comprobante)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.IdConcepto).HasColumnName("ID_Concepto");
            entity.Property(e => e.IdMoneda).HasColumnName("ID_Moneda");
            entity.Property(e => e.MontoTotal)
                .HasColumnType("decimal(20, 2)")
                .HasColumnName("Monto_Total");
            entity.Property(e => e.NroRecibo).HasColumnName("Nro_Recibo");

            entity.HasOne(d => d.IdConceptoNavigation).WithMany(p => p.DetallesRecibos)
                .HasForeignKey(d => d.IdConcepto)
                .HasConstraintName("FK_DetRecibo_Concepto");

            entity.HasOne(d => d.IdMonedaNavigation).WithMany(p => p.DetallesRecibos)
                .HasForeignKey(d => d.IdMoneda)
                .HasConstraintName("FK_DetRecibo_Moneda");

            entity.HasOne(d => d.NroReciboNavigation).WithMany(p => p.DetallesRecibos)
                .HasForeignKey(d => d.NroRecibo)
                .HasConstraintName("FK_DetRecibo_Recibo");
        });

        modelBuilder.Entity<Direccione>(entity =>
        {
            entity.HasKey(e => e.IdDireccion).HasName("PK_ID_direccion");

            entity.Property(e => e.IdDireccion).HasColumnName("ID_direccion");
            entity.Property(e => e.Calle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CodigoPostal)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Codigo_Postal");
            entity.Property(e => e.IdBarrio).HasColumnName("ID_barrio");
            entity.Property(e => e.Numeracion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdBarrioNavigation).WithMany(p => p.Direcciones)
                .HasForeignKey(d => d.IdBarrio)
                .HasConstraintName("FK_Direccion_Barrio");
        });

        modelBuilder.Entity<Disponible>(entity =>
        {
            entity.HasKey(e => e.IdDisponible).HasName("PK_id_disponible");

            entity.Property(e => e.IdDisponible).HasColumnName("Id_disponible");
            entity.Property(e => e.Detalle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK_ID_Empleado");

            entity.Property(e => e.IdEmpleado).HasColumnName("ID_Empleado");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Cbu)
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("CBU");
            entity.Property(e => e.IdDireccion).HasColumnName("ID_Direccion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("ID_tipo_doc");
            entity.Property(e => e.IdTipoEmpleado).HasColumnName("ID_Tipo_Empleado");
            entity.Property(e => e.MailContacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Mail_Contacto");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Empleado_Direccion");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdTipoDoc)
                .HasConstraintName("FK_Empleados_tipo_doc");

            entity.HasOne(d => d.IdTipoEmpleadoNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdTipoEmpleado)
                .HasConstraintName("FK_Empleado_Tipo");
        });

        modelBuilder.Entity<Inmueble>(entity =>
        {
            entity.HasKey(e => e.IdInmueble).HasName("PK_ID_Inmueble");

            entity.Property(e => e.IdInmueble).HasColumnName("ID_Inmueble");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.IdInquilino).HasColumnName("ID_inquilino");
            entity.Property(e => e.IdLibreDeuda).HasColumnName("ID_libre_deuda");
            entity.Property(e => e.IdPropietario).HasColumnName("ID_Propietario");
            entity.Property(e => e.NombreInmueble)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("Nombre_Inmueble");

            entity.HasOne(d => d.IdInquilinoNavigation).WithMany(p => p.Inmuebles)
                .HasForeignKey(d => d.IdInquilino)
                .HasConstraintName("FK_Inmueble_Inquilino");

            entity.HasOne(d => d.IdLibreDeudaNavigation).WithMany(p => p.Inmuebles)
                .HasForeignKey(d => d.IdLibreDeuda)
                .HasConstraintName("FK_Inmueble_LibreDeuda");

            entity.HasOne(d => d.IdPropietarioNavigation).WithMany(p => p.Inmuebles)
                .HasForeignKey(d => d.IdPropietario)
                .HasConstraintName("FK_Inmueble_Propietario");
        });

        modelBuilder.Entity<Inquilino>(entity =>
        {
            entity.HasKey(e => e.IdInquilino).HasName("PK_ID_Inquilino");

            entity.Property(e => e.IdInquilino).HasColumnName("ID_Inquilino");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Cbu)
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("CBU");
            entity.Property(e => e.IdDireccion).HasColumnName("ID_Direccion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("ID_tipo_doc");
            entity.Property(e => e.MailContacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Mail_Contacto");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Inquilinos)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Inquilino_Direccion");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Inquilinos)
                .HasForeignKey(d => d.IdTipoDoc)
                .HasConstraintName("FK_Inquilinos_tipo_doc");
        });

        modelBuilder.Entity<LibreDeudum>(entity =>
        {
            entity.HasKey(e => e.IdLibreDeuda).HasName("PK_ID_Libre_Deuda");

            entity.ToTable("Libre_Deuda");

            entity.Property(e => e.IdLibreDeuda).HasColumnName("ID_Libre_Deuda");
            entity.Property(e => e.Detalle)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Localidade>(entity =>
        {
            entity.HasKey(e => e.IdLocalidad).HasName("PK_ID_localidad");

            entity.Property(e => e.IdLocalidad).HasColumnName("ID_localidad");
            entity.Property(e => e.Localidad)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("localidad");

            entity.HasOne(d => d.ProvinciaNavigation).WithMany(p => p.Localidades)
                .HasForeignKey(d => d.Provincia)
                .HasConstraintName("FK_Localidad_Provincia");
        });

        modelBuilder.Entity<Moneda>(entity =>
        {
            entity.HasKey(e => e.IdMoneda).HasName("PK_id_moneda");

            entity.Property(e => e.IdMoneda).HasColumnName("Id_moneda");
            entity.Property(e => e.TipoMoneda)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("Tipo_moneda");
        });

        modelBuilder.Entity<Obrero>(entity =>
        {
            entity.HasKey(e => e.IdObrero).HasName("PK_ID_Obrero");

            entity.ToTable("OBREROS");

            entity.Property(e => e.IdObrero).HasColumnName("ID_Obrero");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Cbu)
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("CBU");
            entity.Property(e => e.IdDireccion).HasColumnName("ID_Direccion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("ID_tipo_doc");
            entity.Property(e => e.IdTipoObrero).HasColumnName("ID_Tipo_obrero");
            entity.Property(e => e.MailContacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Mail_Contacto");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Obreros)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Obrero_Direccion");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Obreros)
                .HasForeignKey(d => d.IdTipoDoc)
                .HasConstraintName("FK_Obreros_tipo_doc");

            entity.HasOne(d => d.IdTipoObreroNavigation).WithMany(p => p.Obreros)
                .HasForeignKey(d => d.IdTipoObrero)
                .HasConstraintName("FK_Obrero_TipoObrero");
        });

        modelBuilder.Entity<Propietario>(entity =>
        {
            entity.HasKey(e => e.IdPropietario).HasName("PK_ID_Propietario");

            entity.Property(e => e.IdPropietario).HasColumnName("ID_Propietario");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Cbu)
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("CBU");
            entity.Property(e => e.IdDireccion).HasColumnName("ID_Direccion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("ID_tipo_doc");
            entity.Property(e => e.MailContacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Mail_Contacto");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Propietarios)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Propietario_Direccion");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Propietarios)
                .HasForeignKey(d => d.IdTipoDoc)
                .HasConstraintName("FK_Propietario_tipo_doc");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.HasKey(e => e.IdProvincia).HasName("PK_ID_provincia");

            entity.Property(e => e.IdProvincia).HasColumnName("ID_provincia");
            entity.Property(e => e.Provincia1)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("provincia");
        });

        modelBuilder.Entity<Recibo>(entity =>
        {
            entity.HasKey(e => e.NroRecibo).HasName("PK_Nro_Recibo");

            entity.Property(e => e.NroRecibo).HasColumnName("Nro_Recibo");
            entity.Property(e => e.EstadoRecibo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Estado_Recibo");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdContrato).HasColumnName("Id_Contrato");
            entity.Property(e => e.IdDetalleInmueble).HasColumnName("ID_Detalle_Inmueble");
            entity.Property(e => e.IdInquilino).HasColumnName("ID_Inquilino");
            entity.Property(e => e.IdPropietario).HasColumnName("ID_Propietario");
            entity.Property(e => e.IdTipoPago).HasColumnName("ID_Tipo_Pago");

            entity.HasOne(d => d.IdContratoNavigation).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.IdContrato)
                .HasConstraintName("fk_id_contrato");

            entity.HasOne(d => d.IdDetalleInmuebleNavigation).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.IdDetalleInmueble)
                .HasConstraintName("FK_Recibo_DetalleInmueble");

            entity.HasOne(d => d.IdInquilinoNavigation).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.IdInquilino)
                .HasConstraintName("FK_Recibo_Inquilino");

            entity.HasOne(d => d.IdPropietarioNavigation).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.IdPropietario)
                .HasConstraintName("FK_Recibo_Propietario");

            entity.HasOne(d => d.IdTipoPagoNavigation).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.IdTipoPago)
                .HasConstraintName("FK_Recibo_TipoPago");
        });

        modelBuilder.Entity<Servicio>(entity =>
        {
            entity.HasKey(e => e.IdServicio).HasName("PK_id_servicio");

            entity.Property(e => e.IdServicio).HasColumnName("Id_servicio");
            entity.Property(e => e.CuentaServicio)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("Cuenta_Servicio");
        });

        modelBuilder.Entity<TipoObrero>(entity =>
        {
            entity.HasKey(e => e.IdTipoObrero).HasName("PK_ID_Tipo_obrero");

            entity.ToTable("Tipo_Obreros");

            entity.Property(e => e.IdTipoObrero).HasColumnName("ID_Tipo_obrero");
            entity.Property(e => e.TipoObrero1)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("Tipo_Obrero");
        });

        modelBuilder.Entity<TiposCambio>(entity =>
        {
            entity.HasKey(e => e.IdTipoCambio).HasName("PK_ID_Tipo_Cambio");

            entity.ToTable("Tipos_Cambios");

            entity.Property(e => e.IdTipoCambio).HasColumnName("ID_Tipo_Cambio");
            entity.Property(e => e.IdMoneda).HasColumnName("ID_Moneda");
            entity.Property(e => e.ValorCambio).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.IdMonedaNavigation).WithMany(p => p.TiposCambios)
                .HasForeignKey(d => d.IdMoneda)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TipoCambio_Moneda");
        });

        modelBuilder.Entity<TiposDoc>(entity =>
        {
            entity.HasKey(e => e.IdTipoDoc).HasName("PK_ID_tipo_doc");

            entity.ToTable("Tipos_doc");

            entity.Property(e => e.IdTipoDoc).HasColumnName("ID_tipo_doc");
            entity.Property(e => e.DescripcionDoc)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("descripcion_doc");
        });

        modelBuilder.Entity<TiposEmpleado>(entity =>
        {
            entity.HasKey(e => e.IdTipoEmpleado).HasName("PK_ID_Tipo_empleado");

            entity.ToTable("Tipos_Empleados");

            entity.Property(e => e.IdTipoEmpleado).HasColumnName("ID_Tipo_Empleado");
            entity.Property(e => e.TipoEmpleado)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("Tipo_Empleado");
        });

        modelBuilder.Entity<TiposInmueble>(entity =>
        {
            entity.HasKey(e => e.IdTipoInmueble).HasName("PK_ID_Tipo_Inmueble");

            entity.ToTable("Tipos_Inmuebles");

            entity.Property(e => e.IdTipoInmueble).HasColumnName("ID_Tipo_Inmueble");
            entity.Property(e => e.TipoInmueble)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Tipo_Inmueble");
        });

        modelBuilder.Entity<TiposPago>(entity =>
        {
            entity.HasKey(e => e.IdTipoPago).HasName("PK_id_tipo_pago");

            entity.ToTable("Tipos_Pagos");

            entity.Property(e => e.IdTipoPago).HasColumnName("ID_tipo_pago");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TipoPago)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Tipo_pago");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}