// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Inmobiliaria.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Inmobiliaria.Models
{
    public partial class Propiedades_InmobiliariasContext
    {
        private IPropiedades_InmobiliariasContextProcedures _procedures;

        public virtual IPropiedades_InmobiliariasContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Propiedades_InmobiliariasContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPropiedades_InmobiliariasContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Propiedades_InmobiliariasContextProcedures : IPropiedades_InmobiliariasContextProcedures
    {
        private readonly Propiedades_InmobiliariasContext _context;

        public Propiedades_InmobiliariasContextProcedures(Propiedades_InmobiliariasContext context)
        {
            _context = context;
        }

        public virtual async Task<List<pa_contratos_detalladosResult>> pa_contratos_detalladosAsync(int? idPropietario, int? idInquilino, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdPropietario",
                    Value = idPropietario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IdInquilino",
                    Value = idInquilino ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<pa_contratos_detalladosResult>("EXEC @returnValue = [dbo].[pa_contratos_detallados] @IdPropietario = @IdPropietario, @IdInquilino = @IdInquilino", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<pa_contratos_vigentesResult>> pa_contratos_vigentesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<pa_contratos_vigentesResult>("EXEC @returnValue = [dbo].[pa_contratos_vigentes]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<pa_recibos_por_inquilinoResult>> pa_recibos_por_inquilinoAsync(int? idInquilino, DateOnly? desde, DateOnly? hasta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdInquilino",
                    Value = idInquilino ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Desde",
                    Value = desde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Hasta",
                    Value = hasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<pa_recibos_por_inquilinoResult>("EXEC @returnValue = [dbo].[pa_recibos_por_inquilino] @IdInquilino = @IdInquilino, @Desde = @Desde, @Hasta = @Hasta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
