// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Recibo
{
    public int NroRecibo { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? IdInquilino { get; set; }

    public int? IdPropietario { get; set; }

    public int? IdDetalleInmueble { get; set; }

    public int? IdTipoPago { get; set; }

    public string EstadoRecibo { get; set; }

    public int? IdContrato { get; set; }

    public virtual ICollection<DetallesRecibo> DetallesRecibos { get; set; } = new List<DetallesRecibo>();

    public virtual Contrato IdContratoNavigation { get; set; }

    public virtual DetallesInmueble IdDetalleInmuebleNavigation { get; set; }

    public virtual Inquilino IdInquilinoNavigation { get; set; }

    public virtual Propietario IdPropietarioNavigation { get; set; }

    public virtual TiposPago IdTipoPagoNavigation { get; set; }
}