// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class Servicio
{
    public int IdServicio { get; set; }

    public string CuentaServicio { get; set; }
}