// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class TiposCambio
{
    public int IdTipoCambio { get; set; }

    public int IdMoneda { get; set; }

    public decimal ValorCambio { get; set; }

    public virtual Moneda IdMonedaNavigation { get; set; }
}