// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class TipoObrero
{
    public int IdTipoObrero { get; set; }

    public string TipoObrero1 { get; set; }

    public virtual ICollection<Obrero> Obreros { get; set; } = new List<Obrero>();
}