// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class TiposPago
{
    public int IdTipoPago { get; set; }

    public string TipoPago { get; set; }

    public string Descripcion { get; set; }

    public int? Recargo { get; set; }

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();
}