// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Models;

public partial class TiposDoc
{
    public int IdTipoDoc { get; set; }

    public string DescripcionDoc { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual ICollection<Inquilino> Inquilinos { get; set; } = new List<Inquilino>();

    public virtual ICollection<Obrero> Obreros { get; set; } = new List<Obrero>();

    public virtual ICollection<Propietario> Propietarios { get; set; } = new List<Propietario>();
}